env: production
description: &description "백엔드 개발자 반정훈의 기술 블로그입니다."
author: junghoon-vans

defaultTheme: auto
ShowReadingTime: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowCodeCopyButtons: true
showtoc: true
comments: true

homeInfoParams:
  Title: "Hello World!"
  Content: *description

socialIcons:
  - name: github
    url: "https://github.com/junghoon-vans"
  - name: X
    url: "https://x.com/junghoon_vans"
  - name: linkedin
    url: "https://www.linkedin.com/in/junghoon-ban"
  - name: email
    url: "mailto:junghoon.ban@gmail.com"

editPost:
  URL: "https://github.com/junghoon-vans/vanslog/tree/main/content"
  Text: "수정"
  appendFilePath: true
